### ISSUE TITLE
Branch-issue-Committing-naming-convention

### ISSUE THREAD

**Issue by Ibrahim86Ali** [HYF-Class20/agile-development-group2-loruki#3]
# Respect

## $${\color{lightgreen}  Branch - Convention -please-follow - this - pattern- when- branching-issue }$$

- git branch <category/reference/description-in-kebab-case>

## $${\color{lightgreen}  Committing - Convention -please-follow - this - pattern- when-Committing   }$$
- git commit -m '<category: do something; do some other things>'

**Comment by GabriellaLohy** [comment]
Noted! 🤓👍

**Comment by talmurshidi** [comment]
Please add the notes to CONSTRAINTS.md file
